# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: test
      - task: smoke
      - task: lint

  test:
    cmds:
      - mkdir -p bin
      - gotestsum -- -coverprofile=bin/coverage.out ./...

  lint:
    cmds:
      - golangci-lint run

  browser:
    cmds:
      - go tool cover -html=bin/coverage.out

  smoke:
    cmds:
      - go run ./examples/cliflags -h
      - go run ./examples/download -h
      - go run ./examples/phonex8 -h
      - go run ./examples/usercontext -h

  deps:
    cmds:
      - go install gotest.tools/gotestsum@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3
