# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: test
      - task: build

  test:
    cmds:
      - mkdir -p bin
      - gotestsum -- -coverprofile=bin/coverage.out ./...

  browser:
    cmds:
      - go tool cover -html=bin/coverage.out

  build:
    cmds:
      - go build ./...

  deps:
    cmds:
      - go install gotest.tools/gotestsum@latest
